# ./role/molecule_handler/tasks/networks/remove.yaml
- name: Remove network
  nsys.libvirt.network.network:
    name: "{{ network.name }}"
    state: absent
  loop: "{{ NETWORK_SPECS }}"
  when: network.name != 'default'
  loop_control:
    loop_var: network
    index_var: network_index