# ./role/molecule_handler/tasks/devices/_process_interfaces.yaml
- name: Refresh Networks
  nsys.libvirt.common.refresh_resources:
    resource: network
    name: "{{ item.reference }}"
  loop: "{{ INTERFACE_REFERENCE }}"

- name: Process network interface attachments
  nsys.libvirt.network.attach:
    network_name: "{{ interface_ref.reference }}"
    domain_name: "{{ interface_ref.target_domain }}"
    connected: "{{ interface_ref.connected | default(true) }}"
    mac_address: "{{ interface_ref.mac | default(omit) }}"
  loop: "{{ INTERFACE_REFERENCE }}"
  loop_control:
    loop_var: interface_ref

- name: Update dhcp reservation if mac and ip are provided
  nsys.libvirt.network.update_dhcp_reservation:
    network_name: "{{ interface_ref.reference }}"
    domain_name: "{{ interface_ref.target_domain }}"
    ip_address: "{{ interface_ref.ip | ansible.utils.ipaddr('address') }}"
    mac_address: "{{ interface_ref.mac }}"
  loop: "{{ INTERFACE_REFERENCE }}"
  loop_control:
    loop_var: interface_ref
  when: interface_ref.ip is defined and interface_ref.mac is defined
