# ./role/molecule_handler/tasks/pools/create.yaml
- name: Ensure tha storage pool directory exists
  ansible.builtin.file:
    path: "{{ POOL_DIR }}"
    state: directory
    mode: '0755'
    recurse: yes

- name: Create a directory storage pool
  nsys.libvirt.storage_pool:
    name: "{{ POOL_NAME }}"
    pool_type: dir  # Must specify type when creating
    target_path: "{{ POOL_DIR }}"
    state: active
    autostart: true # Will start on boot
    uri: "{{ URI }}"
