# ./roles/domains/tasks/_remove.yaml

- name: Set list to domains to be removed
  ansible.builtin.set_fact:
    domains_to_remove: "{{ DOMAIN_SPECS | map(attribute='name') | list }}"

- name: Force full turn off Domains - since we delete them anyway
  nsys.libvirt.domain_power_state:
    name: "{{ item }}"
    state: poweroff
    force: true
    uri: "{{ URI }}"
  loop: "{{ domains_to_remove }}"

- name: Remove virtual machines
  community.libvirt.virt:
    name: "{{ item }}"
    flags:
    - managed_save
    - snapshots_metadata
    - nvram
    - checkpoints_metadata
    command: undefine
    force: true
    uri: "{{ URI }}"
  loop: "{{ domains_to_remove }}"