# ./roles/domains/tasks/_create.yaml

- name: Create virtual machines
  nsys.libvirt.domain:
    name: "{{ item.name }}"
    state: present
    memory: "{{ item.memory }}"
    vcpu: "{{ item.cpu }}"
    uri: "{{ URI }}"
  loop: "{{ DOMAIN_SPECS }}"