# ./role/molecule_handler/tasks/clones/create.yaml
- name: Create a full clone of a Domain
  nsys.libvirt.domain.clone_domain:
    name: "{{ clone.source_name}}"
    clone_name: "{{ clone.name }}"
    linked_clone: "{{ clone.linked_clone | default(false) }}"
    target_storage_pool: "{{ POOL_NAME }}"
  loop: "{{ CLONE_SPECS }}"
  loop_control:
    loop_var: clone
