# ./role/molecule_handler/tasks/clones/remove.yaml
- name: Remove virtual machines
  nsys.libvirt.domain.domain:
    name: "{{ item.name }}"
    state: absent
    uri: "{{ URI }}"
  loop: "{{ CLONE_SPECS }}"