# ./role/molecule_handler/tasks/disks/remove.yaml
    - name: Remove volume for disks
      nsys.libvirt.storage.volume:
        name: "{{ disk.name }}"
        pool: "{{ POOL_NAME }}"
        state: absent
      loop: "{{ DISK_SPECS }}"
      loop_control:
        loop_var: disk
