---
- name: Converge
  hosts: localhost
  vars:
    MOLECULE_FILES_DIR: "{{ playbook_dir }}/../molecule/default/files"
    MOLECULE_TEST_BASE_DIR: "/tmp/molecule"
  gather_facts: false
  tasks:
  - name: Selftest verifier
    # we check if the verifier is possible to work since we rely on lookup modules that are part of this repo
    # therefore we use the volume lookup if any volumes are present in the default pool
    # not the best test, but it is a start
    ansible.builtin.assert:
      that:
      - lookup('nsys.libvirt.storage.info', pool='default') is not none

  - name: include pool creations
    ansible.builtin.include_tasks: tasks/create_pools.yaml

  - name: include volumen import/creations
    ansible.builtin.include_tasks: tasks/create_volumes.yaml
    loop:
    - pool1
    - pool2
    - pool3

  - name: include pool creations
    ansible.builtin.include_tasks: pools/create.yaml