# ./roles/libvirt_disks/tasks/_create_disk.yml
---
- name: "Create volume for physical disk {{ disk.name }}"
  nsys.libvirt.libvirt_volume:
    name: "{{ disk.name }}"
    pool: "{{ pool_name }}"
    format: "{{ disk.format | default('qcow2') }}"
    capacity: "{{ disk.capacity | default('10') }}"
    allocation: "{{ disk.allocation | default('1') }}"
    state: present
