namespace: nsys
name: libvirt
version: 0.2.1
readme: README.md
authors:
  - N-One Systems (@n-one-systems)
description: Collection for managing libvirt resources
dependencies:
  "community.general": ">=10.0.1,<11.0.0"
  "ansible.posix":  ">=1.6.0,<2.0.0"
license:
  - GPL-3.0-or-later
tags:
  - libvirt
  - virtualization
  - system
repository: https://github.com/n-one-systems/ansible-collection-libvirt
documentation: https://github.com/n-one-systems/ansible-collection-libvirt/tree/main/docs
homepage: https://github.com/n-one-systems/ansible-collection-libvirt
issues: https://github.com/n-one-systems/ansible-collection-libvirt/issues
build_ignore: []
