- name: Deactivate libvirt storage pool if active
  community.libvirt.virt_pool:
    name: "{{ pool_name }}"

    state: inactive

- name: Remove libvirt storage pool from libvirt
  community.libvirt.virt_pool:
    name: "{{ pool_name }}"
    uri: "{{ uri }}"
    state: absent

- name: Ensure libvirt storage pool directory is removed
  ansible.builtin.file:
    path: "{{ pool_dir }}"
    state: absent
