---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: default
provisioner:
  name: ansible
  config_options:
    libvirt_defaults: {}
      # the below values are here to show the defaults that get set
      # storage_pool_base_dir: "/var/tmp/"
      # uri: qemu:///system
      # oob_network:
      #   cidr: "192.0.2.0/24"  # OVERWRITE THIS if you want to have multiple molecule environments
      #   mac_prefix: "52:54:00"
      #   NOTE: DHCP is enabled by default and can not be disabled
    defaults:
      interpreter_python: auto_silent
verifier:
  name: ansible
platforms:
  - name: clone-instance
    reference: debian12
    type: clone
    power_state: running
  - name: first-instance
    type: vm
    power_state: poweroff
    cloud_init: false
    cpu: 1
    memory: 1024
    interfaces:
    - network: default
    - network: custom-net
      ip: 192.168.18.22/24
      connected: false
    disks:
    - name: system
      capacity: 15
    - name: install-iso
      path: "./files/dsl.iso"
  - name: second-instance
    type: vm
    cloud_init: true
    cpu: 2
    memory: 2048
    interfaces:
      - network: default
      - network: custom-net
        ip: 192.168.18.100/24
    disks:
      - name: system
        capacity: 15
        boot_order: 1
  - name: internal-net
    type: network
    forwarding: route
    cidr: 172.19.0.0/24
    dhcp:
      start: 172.19.0.10
      end: 172.19.0.50
  - name: custom-net
    type: network
    forwarding: nat
    cidr: 192.168.18.0/24
  - name: USB-DRIVE
    type: disk
    capacity: 8
    format: qcow2