- name: create disk image
  hosts: localhost
  tasks:
  - name: Create a libvirt volume
    nsys.libvirt.libvirt_volume:
      name: my_new_volume
      pool: default
      capacity: 10G
      allocation: 1G
      format: qcow2
      state: present
  
  #- name: Delete a libvirt volume
  #  libvirt_volume:
  #    name: my_old_volume
  #    pool: default
  #    state: absent
