# Sample disk creation playbook

- name: create disk image
  hosts: localhost
  tasks:
  - name: Download CirrOS image
    ansible.builtin.get_url:
      url: https://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
      dest: /tmp/cirros-0.6.2-x86_64-disk.img
      mode: '0644'
    register: downloaded_image
  - name: Import an existing qcow2 image
    nsys.libvirt.libvirt_volume:
      name: imported_volume
      pool: default
      import_image: "{{ downloaded_image.dest }}"
      state: present
