# ./roles/molecule_transformer/tasks/_clone.yaml

- name: Extract network entries
  ansible.builtin.set_fact:
    _clone_entries: "{{ yaml_content | selectattr('type', 'equalto', 'clone') | list }}"

- name: Process cloning Domain basics
  ansible.builtin.set_fact:
    _clones_as_dict: "{{ _clones_as_dict | default([]) + [_transformed_vm] }}"
  vars:
    _transformed_vm:
      source_name: "{{ clone.reference }}"
      type: "{{ clone.type }}"
      power_state: "{{ clone.power_state | default('running') }}"
      name: "{{ clone.name }}"
      linked_clone: "{{ clone.linked_clone | default(false) }}"
  loop: "{{ _clone_entries }}"
  loop_control:
    loop_var: clone
  when: _clone_entries is defined

- name: Assign cloning information
  ansible.builtin.set_fact:
      CLONES: "{{ _clones_as_dict | default([]) }}"

- name: DEBUG - Clones as dict
  ansible.builtin.debug:
      msg: "{{ CLONES }}"
  when: ansible_verbosity >= 1


