# ./roles/molecule_transformer/tasks/_domain.yaml

# Takes a molecule provided yaml structure and returns a list of VMs with their interfaces and disks as references
# RETURNS:
#   DOMAIN_SPECS        - spec of Domains to create/modify

- name: Initialize Domain list
  set_fact:
    _domain_as_dict: []

- name: Transform Domain information
  ansible.builtin.set_fact:
    _domain_as_dict: "{{ _domain_as_dict + [_transformed_domain] }}"
  vars:
    _transformed_domain:
      name: "{{ _domain.name }}"
      type: "{{ _domain.type }}"
      cpu: "{{ _domain.cpu }}"
      memory: "{{ _domain.memory }}"
      power_state: "{{ _domain.power_state | default('running') }}"
      cloud_init: "{{ _domain.cloud_init | default(true) }}"
  loop: "{{ _vm_specs }}"
  loop_control:
    loop_var: _domain

- name: Assign domain information
  set_fact:
    DOMAIN_SPECS: "{{ _domain_as_dict }}"

- name: DEBUG - Rendered dict for Domains
  ansible.builtin.debug:
    msg:
    - "{{ DOMAIN_SPECS }}"
  when: ansible_verbosity >= 1
