# ./roles/molecule_transformer/tasks/_references.yaml

# Takes a molecule provided yaml structure and returns a list references to disks and interfaces that should be attached to the domains
# RETURNS:
#   INTERFACE_REFERENCE - list of interfaces to attach to the domains
#   DISK_REFERENCE - list of disks to attach to the domains

- name: Initialize interface and disk references for this domain
  ansible.builtin.set_fact:
    _interface_reference: []
    _disk_reference: []

- name: Creates Interface Reference
  ansible.builtin.set_fact:
    _interface_reference: "{{ _interface_reference | default([]) + [loop_if] }}"
  vars:
    loop_if:
      reference: "{{ PROJECT_NAME ~ '-' ~ interface.network if interface.network != 'default' else 'default' }}"
      ip: "{{interface.ip | default(omit)}}"
      target_domain: "{{domain.name}}"
      connected: "{{interface.connected | default(true)}}"
  loop: "{{ domain.interfaces }}"
  loop_control:
    loop_var: interface
  when: domain.interfaces is defined

- name: Add oob interface to interface reference
  ansible.builtin.set_fact:
    _interface_reference: "{{ _interface_reference | default([]) + [loop_if] }}"
  vars:
    loop_if:
      reference: "{{ default_molecule_oob_network_name }}"
      ip: >-
        {{ default_molecule_oob_network_address | 
        ansible.utils.ipaddr( 244 | random(seed=PROJECT_NAME+domain.name) + 10 ) | 
        ansible.utils.ipaddr('host') }}
      mac: "{{ default_molecule_oob_mac_prefix | community.general.random_mac(seed=PROJECT_NAME+domain.name) }}"
      target_domain: "{{ domain.name }}"
      connected: "{{true}}"

- name: Creates Disk Reference
  ansible.builtin.set_fact:
    _disk_reference: "{{ _disk_reference | default([]) + [loop_disk] }}"
  vars:
    loop_disk:
      reference: "{{ PROJECT_NAME ~ '-' ~ domain.name ~ '-' ~ disk.name }}"
      target_domain: "{{ domain.name }}"
      boot_order: "{{ disk.boot_order | default(omit) }}"
  loop: "{{ domain.disks }}"
  loop_control:
    loop_var: disk
  when: domain.disks is defined

- name: DEBUG - Rendered to attach interfaces and disks
  ansible.builtin.debug:
    msg:
    - "{{ _disk_reference }}"
    - "{{ _interface_reference }}"
  when: ansible_verbosity >= 3

- name: Append local vars to export lists
  ansible.builtin.set_fact:
    INTERFACE_REFERENCE: "{{ INTERFACE_REFERENCE | default([]) + _interface_reference }}"
    DISK_REFERENCE: "{{ DISK_REFERENCE | default([]) + _disk_reference }}"