---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: default
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
verifier:
  name: ansible
platforms:
- name: clone-instance
  reference: debian12
  type: clone
  power_state: running