# ./roles/molecule_transformer/defaults/main.yaml

storage_pool_base_dir: "/var/tmp/"
URI: "qemu:///system"

_oob_network:
  name: "{{ PROJECT_NAME }}-molecule-oob"
  cidr: "192.0.2.0/24"
  # RFC 5737 TEST-NET-1 address block can be used for documentation and examples
  # we use it as oob NAT network for molecule, to avoid conflicts with real networks
  mac_prefix: "52:54:00"
  dhcp: true
  is_oob: true