# ./roles/storage_pool/tasks/_create.yaml

- name: Ensure libvirt storage pool directory exists
  ansible.builtin.file:
    path: "{{ POOL_DIR }}"
    state: directory
    mode: '0755'
  register: libvirt_pool_creation

- name: Ensure libvirt storage pool is defined
  community.libvirt.virt_pool:
    name: "{{ POOL_NAME }}"
    state: present
    uri: "{{ URI }}"
    xml: "{{lookup('template', 'storage-pool-template.xml.j2')}}"

- name: Activate libvirt storage pool if not active
  community.libvirt.virt_pool:
    name: "{{ POOL_NAME }}"
    uri: "{{ URI }}"
    state: active

- name: Ensure of auto start libvirt storage pool
  community.libvirt.virt_pool:
    name: "{{ POOL_NAME }}"
    uri: "{{ URI }}"
    autostart: true