- name: Deactivate libvirt storage pool if active
  community.libvirt.virt_pool:
    name: "{{ POOL_NAME }}"
    uri: "{{ URI }}"
    state: inactive

- name: Remove libvirt storage pool from libvirt
  community.libvirt.virt_pool:
    name: "{{ POOL_NAME }}"
    uri: "{{ URI }}"
    state: absent

- name: Ensure libvirt storage pool directory is removed
  ansible.builtin.file:
    path: "{{ POOL_DIR }}"
    state: absent
