# ./roles/molecule_handler/tasks/_populate.yaml
# nsys-ai-claude-3.5

- name: Initialize instance configuration
  ansible.builtin.set_fact:
    instance_conf: []

- name: Get domain information from libvirt
  nsys.libvirt.domain_info:
    name: "{{ item.name }}"
  loop: "{{ DOMAIN_SPECS }}"
  register: domain_info

- name: Get network information for default molecule OOB network
  nsys.libvirt.network_info:
    name: "{{ default_molecule_oob_network_name }}"
  register: oob_network_info

- name: Get interface references for each domain
  ansible.builtin.set_fact:
    domain_interfaces: "{{ INTERFACE_REFERENCE | selectattr('target_domain', 'equalto', item.name) | list }}"
  loop: "{{ DOMAIN_SPECS }}"
  register: domain_interfaces

- name: Build instance configuration dictionary
  ansible.builtin.set_fact:
    instance_conf: "{{ instance_conf + [host_config] }}"
  vars:
    oob_interface: "{{ domain_interfaces.results[idx].ansible_facts.domain_interfaces | 
                       selectattr('reference', 'equalto', default_molecule_oob_network_name) | first }}"
    ssh_key_private: "{{ lookup('file', ssh_key_path + '/id_' + ssh_key_type) }}"
    host_config:
      instance: "{{ item.name }}"
      address: "{{ oob_interface.ip | ansible.utils.ipaddr('address') }}"
      user: "{{ default_user }}"
      port: 22
      identity_file: "{{ ssh_key_path }}/id_{{ ssh_key_type }}"
      ssh_key_private: "{{ ssh_key_private }}"
      become_method: sudo
      become: true
  loop: "{{ DOMAIN_SPECS }}"
  loop_control:
    index_var: idx

- name: Write instance config file
  ansible.builtin.copy:
    content: |
      # Molecule managed
      # Created by nsys.libvirt.molecule_handler
      {{ instance_conf | to_json | from_json | to_yaml }}
    dest: "{{ molecule_instance_config }}"
    mode: "0600"

- name: Debug instance configuration
  ansible.builtin.debug:
    var: instance_conf
  when: ansible_verbosity >= 1