# ./roles/attach_devices/tasks/_process_disks.yaml
# nsys-ai-claude-3.5

- name: Get grouped data
  ansible.builtin.set_fact:
    grouped_data: "{{ disks_to_process | groupby('target_domain') | list }}"

- name: debug
  ansible.builtin.debug:
    msg: "{{grouped_data}}"

- name: Process disk attachments
  nsys.libvirt.attach_volume:
    pool: "{{ POOL_NAME }}"
    volumes: "{{ item.1 | map(attribute='reference') | list }}"
    name: "{{item.0}}"
  loop: "{{ grouped_data }}"


