# ./roles/attach_devices/tasks/main.yaml
# nsys-ai-claude-3.5

- name: Assert that required variables are defined
  ansible.builtin.assert:
    that:
      - DISK_REFERENCE is defined or INTERFACE_REFERENCE is defined
      - state is defined
      - state in ['present', 'absent']
    quiet: true

- name: Determine devices to process
  ansible.builtin.set_fact:
    disks_to_process: "{{ DISK_REFERENCE | default([]) }}"
    interfaces_to_process: "{{ INTERFACE_REFERENCE | default([]) }}"

- name: Process disks
  when: disks_to_process | length > 0
  ansible.builtin.include_tasks: _process_disks.yaml

#- name: Process interfaces
#  when: interfaces_to_process | length > 0
#  ansible.builtin.include_tasks: _process_interfaces.yaml
