# ./roles/attach_devices/tasks/main.yaml
# nsys-ai-claude-3.5

- name: Assert that required variables are defined
  ansible.builtin.assert:
    that:
      - DISK_REFERENCE is defined or INTERFACE_REFERENCE is defined
      - state is defined
      - state in ['present', 'absent']
    quiet: true

- name: Debug - Disks to process
  ansible.builtin.debug:
    msg:
    - "{{ DISK_REFERENCE }}"
    - "{{ INTERFACE_REFERENCE }}"

- name: Process disks
  when: DISK_REFERENCE | length > 0
  ansible.builtin.include_tasks: _process_disks.yaml
  vars:
    disks_to_process: "{{ DISK_REFERENCE }}"

- name: Process interfaces
  when: INTERFACE_REFERENCE | length > 0
  ansible.builtin.include_tasks: _process_interfaces.yaml
  vars:
    interfaces_to_process: "{{ INTERFACE_REFERENCE }}"